[package]
name = "lzf-qc"
version = "0.0.1"
authors = ["Jan-Erik Rediger <badboy@fnordig.de>"]
description = "Compare lzf-rs to native C library"
license = "BSD-3-Clause"

build = "build.rs"

[dependencies]
quickcheck = "0.2"
libc = "0.2"
lzf = {path = ".."}

[build-dependencies]
gcc = "0.3"
